### ISSUE TITLE
Gantt Chart doesn't work in dev mode with Vaadin 25.1.0

### ISSUE THREAD

**Issue by F-Kamp** [vaadin/quarkus#280]
### Description

After updating to Vaadin 25.1.0 the Gantt Chart component doesn't seem to work anymore when running the application in dev mode. This is printed to the browser console:

```text
GanttResult:8 Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
GanttResult:8 The error has occurred in the JS code: '$0, $1, $2, return $0.updateConfiguration($1,$2)'
FlowClient-UiW1Q_9Y.js:349 Uncaught TypeError: $0.updateConfiguration is not a function
    at Object.eval (eval at Du (FlowClient-UiW1Q_9Y.js:7478:13), <anonymous>:3:11)
    at Du (FlowClient-UiW1Q_9Y.js:7479:11)
    at Cu (FlowClient-UiW1Q_9Y.js:6117:7)
    at Au (FlowClient-UiW1Q_9Y.js:2405:9)
    at Tr (FlowClient-UiW1Q_9Y.js:1766:7)
    at os.ps [as fb] (FlowClient-UiW1Q_9Y.js:8756:7)
    at uC (FlowClient-UiW1Q_9Y.js:5681:28)
    at Wr (FlowClient-UiW1Q_9Y.js:7606:9)
    at ks.ls [as C] (FlowClient-UiW1Q_9Y.js:8745:7)
    at cl (FlowClient-UiW1Q_9Y.js:3817:15)
    at jl.ll [as eb] (FlowClient-UiW1Q_9Y.js:8200:7)
    at fo.go [as I] (FlowClient-UiW1Q_9Y.js:8437:14)
    at FlowClient-UiW1Q_9Y.js:5433:14
```
The Gantt is not displayed in the browser at all.

Funnily enough, when running in production mode, everything works fine - Gantt is displayed and Gantt items are drawn.

### Expected outcome

Dev mode should work

### Minimal reproducible example

```kotlin
@Route("Demo")
class GanttDemo : Div() {

    init {
        val chart = Chart(ChartType.GANTT)
        val configuration = chart.configuration
        
        val projectDevelopmentSeries = createProjectDevelopmentSeries()
        configuration.addSeries(projectDevelopmentSeries)

        add(chart)
    }

    private fun createProjectDevelopmentSeries(): GanttSeries {
        val series = GanttSeries()
        series.name = "Project 1"


        val item = GanttSeriesItem(0, Instant.now(), Instant.now().plusSeconds(12000))
        series.add(item)

        return series
    }
}
```

### Steps to reproduce

Run the application in dev mode and navigate to /Demo

### Environment

- Vaadin / Flow version: 25.1.0
- Java version: 21
- OS version: Windows 11
- Application Server (if applicable): Quarkus 3.32.3

### Browsers

Chrome

**Comment by yuriy-fix** [comment]
@DiegoCardoso , could you please check if any of charts changes could have caused it or it's coming from flow?

**Comment by mcollovati** [comment]
> Funnily enough, when running in production mode, everything works fine

Makes me wonder if there's an old local dev bundle in `src/main/bundles` that for some reasons has not been re-built

**Comment by DiegoCardoso** [comment]
I couldn't reproduce the issue based on the information shared. 

<img width="1280" height="1326" alt="Image" src="https://github.com/user-attachments/assets/b3f75e7f-624a-400b-9397-a4430a460f14" />

Could you provide more info, perhaps a test project where the issue can be reproduced?

**Comment by F-Kamp** [comment]
It took me some time to narrow my project down to figure out what is required to break the dev mode. Now I found the culprit:
My dev-ui is a Quarkus module that references the module ui, which is a plain Vaadin Java library. 

If and (and only if) the ui module contains custom stylesheets under META-INF/resources/frontend/styles, starting the dev-ui will trigger a frontend bundle to be built as soon as I open the browser the first time. That seems to break the dev mode.

I can see my custom stylesheet being used but the Gantt won't be drawn - instead the error I've shown above is displayed in the browser console.

Reproducer project: https://github.com/F-Kamp/vaadin-quarkus-gradle-bug/tree/gantt-broken-dev-mode

**Comment by F-Kamp** [comment]
> > Funnily enough, when running in production mode, everything works fine
> 
> Makes me wonder if there's an old local dev bundle in `src/main/bundles` that for some reasons has not been re-built

I deleted everything by hand multiple times while analyzing the bug. Is there a better way to do that when using Gradle and Quarkus? I know with Maven and the Vaadin Plugin there's a clean-frontend task that can be executed, but I haven't seen anything similar when using the Vaadin Quarkus extension with Gradle.

**Comment by mcollovati** [comment]
The Gradle counterpart of Maven `clean-frontend` (or `dance`) goal is `vaadinClean` (if the Gradle Vaadin plugin is configured)

**Comment by mcollovati** [comment]
@yuriy-fix @DiegoCardoso  if you don't have any objections, the issue can be transferred to `vaadin/quarkus` repository.

**Comment by mcollovati** [comment]
It looks like to me the issue is that you are defining `com.vaadin:vaadin-core-jandex` as a dependency instead of `com.vaadin:vaadin-jandex`.
The core Jandex does not contain any commercial classes, so `Chart` is ignored at runtime in dev mode when looking for frontend stuff. 
The production mode by default uses a bytecode scan, so the class is found.

After updating `gradle/libs.versions.toml` to use `vaadin-jandex` the error disappears for me.

```
#vaadin-jandex = { module = "com.vaadin:vaadin-core-jandex" }
vaadin-jandex = { module = "com.vaadin:vaadin-jandex" }
```

**Comment by mcollovati** [comment]
To make it clear:

* annotated classes are collected by `DevModeStartupListener` and passed to `DevModeClassFinder` that is then used by `FullDependenciesScanner` to search for frontend-related annotations.
* `DevModeStartupListener` implements `ServletContainerInitializer`, the interesting classes are provided to it by the Servlet container
* In Quarkus, the classes are collected by a build step, looking into the computed application Jandex index

So, since `vaadin-core-jandex` does not contain `Chart`, the class is not passed to the `DevModeStartupListener`, preventing the related `@NpmPackage` and `@JsModule` annotations from being processed.

**Comment by F-Kamp** [comment]
Oh wow, totally my bad. Sorry. 

What still confuses me a bit is how a possibly unrelated  `CssImport` breaks the `Chart`. 

In my reproducer project I've added the `CssImport` annotation to a class that actually uses a `Chart`; but in my real project I've added a completely unrelated component with a custom stylesheet. And that still broke my `Chart` - but only with Vaadin 25.1.0. Previous versions worked. And without the `CssImport` the `Chart` works in dev mode even with the `vaadin-core-jandex` dependency in 25.1.0! So I never thought to double-check my dependencies. 
It would be nice if the Vaadin extension could print some kind of warning "You are using pro components but only core jandex".

But no matter why it broke, after fixing the dependency as proposed by you, the dev mode works flawlessly. Thank you!

**Comment by mcollovati** [comment]
`CssImport` causes a dev bundle rebuild (differently from `StyleSheet`). The problem is that the `Chart` class is not found only by the frontend build, not at runtime. So, if using the default dev bundle,  `Chart` frontend stuff is included, but rebuilding it is not added.

**Comment by mcollovati** [comment]
> It would be nice if the Vaadin extension could print some kind of warning "You are using pro components but only core jandex".

That could be an interesting improvement, but not so straightforward to implement, I guess. It would most likely require the same byte code scan done for the production build, but this would take time on startup.

**Comment by mcollovati** [comment]
If no objections, I'll close this issue. 
@F-Kamp feel free to create a new issue for the warning message if you want.

**Comment by F-Kamp** [comment]
> `CssImport` causes a dev bundle rebuild (differently from `StyleSheet`). The problem is that the `Chart` class is not found only by the frontend build, not at runtime. So, if using the default dev bundle, `Chart` frontend stuff is included, but rebuilding it is not added.

I see. 

> That could be an interesting improvement, but not so straightforward to implement, I guess. It would most likely require the same byte code scan done for the production build, but this would take time on startup.

Sounds like it's not really worth it unless you get spammed with bug reports like mine where the user is at fault.
